"""add_alerts_feature

Revision ID: c2a330482d91
Revises: 3d6c89753679
Create Date: 2026-08-14 22:28:26.283971

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2a330482d91"
down_revision: str | Sequence[str] | None = "3d6c89753679"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sensor_id", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_sensor_id"), "alerts", ["sensor_id"], unique=False)
    op.add_column("sensors", sa.Column("threshold", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensors", "threshold")
    op.drop_index(op.f("ix_alerts_sensor_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
