"""fix_alert_created_at_server_default

Revision ID: f6a9e84a9e15
Revises: c2a330482d91
Create Date: 2026-08-18 19:24:44.221948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6a9e84a9e15"
down_revision: str | Sequence[str] | None = "c2a330482d91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),  # <-- ¡AQUÍ!
            nullable=False,
        ),
    )
    op.drop_column("alerts", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("alerts", "created_at")
    # ### end Alembic commands ###
